name: Build Release Image

on:
  push:
    branches:
      - 'main'

jobs:
  build-image:
    name: build image
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_TOKEN }}
      - name: build image
        run: docker build -t afrima/anki-sync-server:24.11 --build-arg NOW="$(date -u +"%Y-%m-%dT%H:%M:%SZ")" .
      - name: push image
        run: docker push afrima/anki-sync-server:24.11
