name: Build Release Image

on:
  push:
    branches:
      - 'main'

jobs:
  build-image:
    name: build image
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_TOKEN }}
      - name: build image
        run: docker build -t afrima/anki-sync-server:25.07.2 -t afrima/anki-sync-server:latest --build-arg NOW="$(date -u +"%Y-%m-%dT%H:%M:%SZ")" .
      - name: Wait for healthchecks
        run: docker run -e SYNC_USER1=test_user_name:test_user_password -d afrima/anki-sync-server:latest | timeout 60s sh -c 'until docker ps | grep afrima/anki-sync-server:latest | grep -q healthy; do echo "Waiting for container to be healthy..."; sleep 2; done'
      - name: push image
        run: docker push afrima/anki-sync-server --all-tags
